# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
    ]
